Expose debug symbol start and end for the language server
privacy-scaling-explorations/chiquito pull request #289
Opened 2024-08-22 09:29 UTC by alxkzmn

We have accidentally made the start and end of debug symbol private, so here's a fix for the language server. Also had to update the halo2 to the latest version because the language server didn't want to compile (there was a missing bound on a variable generic inside the halo2 middleware `Expression`, not sure why Chiquito itself compiled successfully).

2024-08-23 10:24 UTC, rutefig approved these changes
lgtm

2024-08-23 16:47 UTC, leolara requested changes

2024-08-23 16:47 UTC, leolara commented on src/parser/ast/mod.rs
> +pub trait LanguageServerInterface {
@alxkzmn I don't think it is custom in Rust to call Interface to a trait. Also, the interface is used by the Language Server, not an interface to the Language Server.

2024-08-27 13:32 UTC, leolara approved these changes

2024-08-27 16:36 UTC, merged